name: Notify migration changes

on:
  pull_request_target:
    branches: [main]
    paths: [alembic/versions/**]

env:
  message: |
    :bell: Migrations changes detected :bell:
    :mega: Remember to comment "/UpdateDatabase" after review approval for migrations to take effect!

jobs:
  Notify_Migration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for previous comment
        id: notify_comment_search
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body-includes: ${{ env.message }}

      - name: Add comment if no comment exists
        if: ${{ !steps.notify_comment_search.outputs.comment-body }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: ${{ env.message }}

      - name: Add label via GitHub CLI
        run: gh pr edit "$NUMBER" --add-label "database-change"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
